let modeloJson = [
  {
  id: 1,
  name: 'As Marvels ',
  img: 'img/hq720.webp',
  price: 00,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: '  ',
  Link:'https://www.youtube.com/watch?v=eAWt5hqJHmA',
},


  {
  id: 1,
  name: 'Guardiões da Galixa 3',
  img: 'img/g3.jpg',
  price: 00,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: '  ',
  Link:'https://www.youtube.com/watch?v=5UVaA6SGRZA',
},
  {
    id: 2,
    name: 'Homem Formiga 3',
    img: 'img/f1.jpg',
    price: 00,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: '  ',
    Link:'https://www.youtube.com/watch?v=6jIz_8tokvg&t=5s',
  },
  {
    id: 2,
    name: 'Lobisomen da Meia Noite',
    img: 'img/L1.jpg',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Vingadores Guerra Inifinita',
    Link:'https://www.youtube.com/watch?v=8uzyWaH68XY',
  },
  {
    id: 3,
    name: 'Guardiões Natal',
    img: 'img/g3.5.jpg',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Vingadores Ultimato',
    Link:'https://www.youtube.com/watch?v=g6ng8iy-l0U',
  },
  {
    id: 4,
    name: 'Pantera Negra 2',
    img: 'img/p1.jpg',
    price: 19.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Thor Amor e Trovão',
    Link:'https://www.youtube.com/watch?v=FR9iLjOubWc',
  },

  {
  id: 13,
  name: 'Dead Pool 3',
  img: 'img/d4.webp',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=214akTge-r4',
  },
  {
    id: 5,
    name: 'Thor 4',
    img: 'img/f4.jpg',
    price: 19.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Vingadores Era de Ultron',
    Link:'https://www.youtube.com/watch?v=dPcdCZekMQg',
  },
  {
    id: 6,
    name: 'Doutor Estranho 2',
    img: 'img/f8.jpg',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Os Vingadores',
    Link:'https://www.youtube.com/watch?v=X23XCFgdh2M&t=1s',
  },
  {
    id: 7,
    name: 'Ultimate Homem Aranha 3',
    img: 'img/h4.png',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'X-men Fênix Negra ',
    Link:'https://www.youtube.com/watch?v=FDNNHh7TRN0&t=102s',
  },

  {
    id: 8,
    name: 'Morbius',
    img: 'img/m1.jpg',
    price: 10.99,
   // sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Doutor Estranho no Multiverso da Loucura',
    Link:'https://www.youtube.com/watch?v=S55qvOKW5T0',
  },
  {
    id: 8,
    name: 'Venom 2',
    img: 'img/v2.jpg',
    price: 10.99,
   // sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Doutor Estranho no Multiverso da Loucura',
    Link:'https://www.youtube.com/watch?v=7KvioH80zLI',
  },
  {
    id: 9,
    name: 'Eternos ',
    img: 'img/f9.jpg',
    price: 10.99,
    //sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Eternos',
    Link:'https://www.youtube.com/watch?v=zgdDOLMSsVs',
  },

  {
    id: 10,
    name: 'Shang-Chi',
    img: 'img/s2.jpg',
    price: 10.99,
    //sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Capitão América Guerra Civil',
    Link:'https://www.youtube.com/watch?v=AfHiUtxrmiY',
  },

  {
    id: 11,
    name: 'Viuva Negra',
    img: 'img/n1.jpg',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Pantera Negra',
    Link:'https://www.youtube.com/watch?v=uNAxHLp7wv8',
  },

  {
    id: 11,
    name: 'Ultimate Homem Aranha 2',
    img: 'img/h5.jpg',
    price: 10.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Pantera Negra',
    Link:'https://www.youtube.com/watch?v=vaw_8DoqXfk',
  },

  {
    id: 12,
    name: 'Vingadores 4',
    img: 'img/f3.jpg',
    price: 19.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Venom',
    Link:'https://www.youtube.com/watch?v=spJoZReeIeQ',
  },

  {
  id: 13,
  name: 'Capitan Marvel',
  img: 'img/aff.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=yeqDv1dLhxI',
},

{
id: 13,
  name: 'Homem formiga 2',
  img: 'img/ant.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=0HGBv7s1Y7E',
},

{
id: 13,
  name: 'Dead Pool 2',
  img: 'img/d2.jfif',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=a7t-avKlpkc',
},

{
id: 13,
  name: 'Vingadores 3',
  img: 'img/f2.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=htQch8jDZ4s',
},

{
  id: 13,
  name: 'Pantera Negra',
  img: 'img/f11.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=wL4a4MafSjQ',
},

{
  id: 13,
  name: 'Thor 3',
  img: 'img/f14.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=UvNnqWLruXA',
},

{
id: 13,
name: 'Dead Pool',
img: 'img/d3.jfif',
price: 19.99,
sizes: ['Básico', 'Capa Dura ', 'Dourado'],
description: 'Venom',
Link:'https://www.youtube.com/watch?v=Q9X-bAE8KTc',
},
{
  id: 13,
  name: 'Guardiões da Galaxia 2',
  img: 'img/g2.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=4-i8nTNSQFI',
},

{
  id: 13,
  name: 'Doutor Estranho',
  img: 'img/d1.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=rETm4Mr3oGw',
},
{
  id: 13,
  name: 'Venom',
  img: 'img/f12.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=EQxCycVTfcU&t=1s',
},
{
  id: 13,
  name: 'Ultimate Homem Aranha',
  img: 'img/h1.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=2x-2iYxgMFU',
},

{
  id: 13,
  name: 'Capitão América 3',
  img: 'img/c3.jpg',
  price: 19.99,
  sizes: ['Básico', 'Capa Dura ', 'Dourado'],
  description: 'Venom',
  Link:'https://www.youtube.com/watch?v=eLAFMkLnf3M',
},

{
  id: 13,
    name: 'Homem Formiga ',
    img: 'img/f15.jpg',
    price: 19.99,
    sizes: ['Básico', 'Capa Dura ', 'Dourado'],
    description: 'Venom',
    Link:'https://www.youtube.com/watch?v=wITUolzfkwI',
  },

  {
    id: 13,
      name: 'Vingadores 2',
      img: 'img/f5.jpg',
      price: 19.99,
      sizes: ['Básico', 'Capa Dura ', 'Dourado'],
      description: 'Venom',
      Link:'https://www.youtube.com/watch?v=lGO6FcnZ0ek&t=2s',
    },

    {
      id: 13,
        name: 'Guardiões da Galaxia ',
        img: 'img/g1.jpg',
        price: 19.99,
        sizes: ['Básico', 'Capa Dura ', 'Dourado'],
        description: 'Venom',
        Link:'https://www.youtube.com/watch?v=8VN_l57QWyQ&t=6s',
      },
      {
        id: 13,
          name: 'Espetacular Homem Aranha 2',
          img: 'img/ha3.jpg',
          price: 19.99,
          sizes: ['Básico', 'Capa Dura ', 'Dourado'],
          description: 'Venom',
          Link:'https://www.youtube.com/watch?v=PfUDLzyC1cM&t=2s',
        },


      {
        id: 13,
          name: 'Capitão América 2',
          img: 'img/c4.jpg',
          price: 19.99,
          sizes: ['Básico', 'Capa Dura ', 'Dourado'],
          description: 'Venom',
          Link:'https://www.youtube.com/watch?v=Fl89Ym_fQJc',
        },
        
        {
          id: 13,
            name: 'Thor 2',
            img: 'img/t2.jpg',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=Ym5W8ZaWs0A',
          },

          {
          id: 13,
            name: 'Homem de Ferro 3',
            img: 'img/i3.jpg',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=ruFW4s_ZF-4',
          },
          {
            id: 13,
              name: 'Espetacular Homem Aranha ',
              img: 'img/ha2.jpg',
              price: 19.99,
              sizes: ['Básico', 'Capa Dura ', 'Dourado'],
              description: 'Venom',
              Link:'https://www.youtube.com/watch?v=6nzNdpJ3qMo',
            },
          
          {
          id: 13,
            name: 'Vingadores ',
            img: 'img/f6.jpg',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=KeNEGtsCWEk',
          },
          {
          id: 13,
            name: 'Capitão América',
            img: 'img/c1.jpg',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=-006iHDHK34',
          },

          {
          id: 13,
          name: 'Thor',
          img: 'img/t1.jpg',
          price: 19.99,
          sizes: ['Básico', 'Capa Dura ', 'Dourado'],
          description: 'Venom',
          Link:'https://www.youtube.com/watch?v=LVzLGrPxc5A',
        },
        {
          id: 13,
          name: 'Hulk 2  ',
          img: 'img/ul2.jpg',
          price: 19.99,
          sizes: ['Básico', 'Capa Dura ', 'Dourado'],
          description: 'Venom',
          Link:'https://www.youtube.com/watch?v=xbqNb2PFKKA',
        },

        {
          id: 13,
            name: 'Homem de Ferro 2',
            img: 'img/i2.jpg',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=b5qs_RtpkhA',
          },
          
          {
            id: 13,
              name: 'Homem de Ferro ',
              img: 'img/i1.jpg',
              price: 19.99,
              sizes: ['Básico', 'Capa Dura ', 'Dourado'],
              description: 'Venom',
              Link:'https://www.youtube.com/watch?v=8ugaeA-nMTc',
            },
            {
              id: 13,
                name: 'Homem Aranha 3 ',
                img: 'img/h3.jpg',
                price: 19.99,
                sizes: ['Básico', 'Capa Dura ', 'Dourado'],
                description: 'Venom',
                Link:'https://www.youtube.com/watch?v=wPosLpgMtTY',
              },

            {
            id: 13,
            name: 'Homem Aranha 2 ',
            img: 'img/h24.webp',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=1UAzz8ncM68',
          },

          {
            id: 13,
            name: 'Homem Aranha  ',
            img: 'img/h25.webp',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=t06RUxPbp_c',
          },
          {
            id: 13,
            name: 'Hulk  ',
            img: 'img/ul.jfif',
            price: 19.99,
            sizes: ['Básico', 'Capa Dura ', 'Dourado'],
            description: 'Venom',
            Link:'https://www.youtube.com/watch?v=2ErnLuJKQA4',
          },
  
];